### PR TITLE
change the acqlist name

### LINKED ISSUE #19: Acquisition List ID field too long to process downstream
**Describe the bug**
The HySDS `job-coseismic_product-s1gunw-slc_localizer:main` Localizer PGE failed to process an Enumerator `S1-COSEISMIC-GUNW-acq-list-event-iter` acquisition list in the download phase. Specifically, the downstream Localizer PGE complained it was attempting to create a download directory that was too long in terms of its file name. 

Upon investigation of the code, the Localizer PGE uses the `job_id` field that derives from an `id` from an Enumerator acquisition list to create a directory for SLC downloads. [This line fails](https://github.com/hysds/hysds/blob/ccaf62b8bb11dfe8a51c4944a4190d3876f0af59/hysds/job_worker.py#L817) during runtime with the following error:

```
Traceback (most recent call last):
  File "/data/export/home/hysdsops/verdi/ops/hysds/hysds/job_worker.py", line 759, in run_job
    makedirs(job_dir)
  File "/data/export/home/hysdsops/verdi/ops/hysds/hysds/utils.py", line 228, in makedirs
    os.makedirs(dir, mode)
  File "/export/home/hysdsops/verdi/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 36] File name too long: '/data/work/jobs/2021/04/26/06/12/coseismic_product-s1gunw-slc_localizer__main-S1-COSEISMIC-GUNW-acq-list-event-iter_3+3--AOITRACK_eq_usgs_neic_pdl_us7000d0gn_55_Bandare_Lengeh_Iran_130--acquisition-S1A_IW_SLC__1SDV_20210215T142520_20210215T142548_036602_044CD2_BA7A-esa_scihub-20210426T061235.142811Z'
```

**To Reproduce**
1. Go to GRQ and facet upon the latest Coseismic Enumerator `S1-COSEISMIC-GUNW-acq-list-event-iter` datasets
2. Run an On-Demand job against the `coseismic_product-s1gunw-slc_localizer__main` PGE
3. In Mamba (Resource Manager) see how the Localizer fails with the above error

**Expected behavior**
We should really do the following to minimize overall code impact:
1. Shorten the `S1-COSEISMIC-GUNW-acq-list-event-iter` dataset's `id` field to be within the `255 bytes` max length for Unix file names
2. Ensure the `S1-COSEISMIC-GUNW-acq-list-event-iter` dataset's `id` field is kept unique

Recommendation for the above: we should use an `id` naming pattern for `S1-COSEISMIC-GUNW-acq-list-event-iter` dataset entries that reflects the pattern used for the ARIA standard-pipeline. For example, here's an acquisition list ID from the standard pipeline: `S1-GUNW-acqlist-RM-M1S3-TN018-20191028T232823-20191004T232730-poeorb-00d5`. Notice how there are two key components to this unique ID: (1) the date range over which the acqlists apply, and (2) a unique hash

**Screenshots**
n/a

**Environment (please complete the following information):**
- ARIA Factotum VM

**Additional context**
@cmarshak might have more information regarding how the standard pipeline's `id` field was designed (according to @marjo-luc). There may be science use case reasons why an ID like that would be useful.

### PR DESCRIPTION
**Pull request by al-niessner**
Closes #19

### CODE REVIEW

**Comment by al-niessner** [comment]
@riverma 

Make sure you test this before merging. While it passes pylint, some of it is not statically checkable so there is chance of failure. It should work though.

**Comment by cmarshak** [comment]
Per the [issue comment](https://github.com/aria-jpl/coseismic_enumerator/issues/19#issuecomment-827698375), can you please put the following in your ES doc:

+ `AOITrack_id`
+ `post-index`
+ `pre-index`
+ `full_id_hash` - this last one is important for other operators and the way the standard product was designed.

**Comment by riverma** [comment]
Thanks @al-niessner for getting this in so quickly - if you can please add the metadata fields @cmarshak specified above, I'll test it out in our system and report back here.

**Comment by al-niessner** [comment]
This is why I like short and simple requests in a single comment block. I removed the post/pre indices because they were no longer used in the label. Now you want them back.

Now is this the complete request or do you need/want to add more:

### Template

`S1-COSEISMIC-GUNW-acqlist-<asc/dsc>-R<num_of_reference_scenes>S<number_of_secondary_scenes>-TN<track_number with leading zeros so its a 3 digit number>-<first secondary_acquisition_datetime>-<last reference_acquisition_datetime>-poeorb-<first 4 chars of full_id_hash>`

- time format: `<Year><Month><Day>T<Hour><Minute><Second>` with year being 4 digits.
- startime of first secondary and endtime of last reference
- hash item is a json list containing:  
    1. list of ordered reference scenes delimited by a space 
    2. list of ordered secondary scenes delimited by a space

### Additional metadata
+ `AOITrack_id`
+ `post-index`
+ `pre-index`
+ `full_id_hash` - this last one is important for other operators and the way the standard product was designed.

**Comment by cmarshak** [comment]
This is the complete ask from my vantage point. The metadata that is being removed from your name/id is now being stored in ES database. Thank you!

**Comment by riverma** [comment]
Let me kick off a test for this - thank you @al-niessner and @cmarshak !

**Comment by cmarshak** [comment]
@riverma, all the changes haven't been done yet - I was confirming that Al had the scope correct.

**Comment by al-niessner** [comment]
@riverma @cmarshak 

Do a test now. Make sure the label (name) changes are what you thought you asked for. Just do one AOI to save time and ease.

**Comment by al-niessner** [comment]
What is an AOITrack_id? Do you mean the aoi['id']? Or in terms of ES the 'id' of the aoi? There is no keywork AOITrack_id.

post-index, count from 1 or 0? I have been treating the event as 0 so post would count up from 1 but now that it is being redefined how would you like to redefine it?

pre-index, count down or up and start with 1 or 0? Have been counting down with further negative being further from 0 or the event.

When you reply, please just restate the scope from above in a new clean comment with brevity of explanation.

**Comment by cmarshak** [comment]
> What is an AOITrack_id? Do you mean the aoi['id']? Or in terms of ES the 'id' of the aoi? There is no keywork AOITrack_id.

Yes, the `aoi['id']`.

> post-index, count from 1 or 0? I have been treating the event as 0 so post would count up from 1 but now that it is being redefined how would you like to redefine it?

Doesn't matter. Whatever is easiest.

> pre-index, count down or up and start with 1 or 0? Have been counting down with further negative being further from 0 or the event.

I think counting down makes sense as you have been doing it.

> When you reply, please just restate the scope from above in a new clean comment with brevity of explanation.

### Template

`S1-COSEISMIC-GUNW-acqlist-<asc/dsc>-R<num_of_reference_scenes>S<number_of_secondary_scenes>-TN<track_number with leading zeros so its a 3 digit number>-<first secondary_acquisition_datetime>-<last reference_acquisition_datetime>-poeorb-<first 4 chars of full_id_hash>`

- time format: `<Year><Month><Day>T<Hour><Minute><Second>` with year being 4 digits.
- startime of first secondary and endtime of last reference
- hash item is a json list containing:  
    1. list of ordered reference scenes delimited by a space 
    2. list of ordered secondary scenes delimited by a space

### Additional metadata
+ `aoi_track_id` - just the `aoi['id']`
+ `post_index` - counting up from earthquake event starting at 1
+ `pre_index`- counting down from earthquake event starting at 1
+ `full_id_hash` - using the references in the issue ticket and copied below. This is important for other operators and the way the standard product was designed.

```
hashlib.md5(json.dumps([
        ' '.join (sorted (acqlist['master_scenes'])),
        ' '.join (sorted (acqlist['slave_scenes']))
        ]).encode('utf8')).hexdigest()
```

(updated all the keys so they are camel case - honestly it doesn't matter so long as they are there @al-niessner)

**Comment by al-niessner** [comment]
Corrected what looked like a typo in pre-index:

### Template

`S1-COSEISMIC-GUNW-acqlist-<asc/dsc>-R<num_of_reference_scenes>S<number_of_secondary_scenes>-TN<track_number with leading zeros so its a 3 digit number>-<first secondary_acquisition_datetime>-<last reference_acquisition_datetime>-poeorb-<first 4 chars of full_id_hash>`

- time format: `<Year><Month><Day>T<Hour><Minute><Second>` with year being 4 digits.
- startime of first secondary and endtime of last reference
- hash item is a json list containing:  
    1. list of ordered reference scenes delimited by a space 
    2. list of ordered secondary scenes delimited by a space

### Additional metadata
+ `aoi_track_id` - just the `aoi['id']`
+ `post_index` - counting up from earthquake event starting at 1
+ `pre_index`- counting down from earthquake event starting at -1
+ `full_id_hash` - using the references in the issue ticket and copied below. This is important for other operators and the way the standard product was designed.

```
hashlib.md5(json.dumps([
        ' '.join (sorted (acqlist['master_scenes'])),
        ' '.join (sorted (acqlist['slave_scenes']))
        ]).encode('utf8')).hexdigest()
```

**Comment by cmarshak** [comment]
The template and additional metadata above looks good.

**Comment by al-niessner** [comment]
@riverma @cmarshak 

Pylint said it was all good. Cross fingers and hope for the best.

**Comment by riverma** [comment]
Awesome thank you @al-niessner - will deploy this 👍

**Comment by riverma** [comment]
@al-niessner - deployed, executed and received the below error in `_stderr`:

```
Traceback (most recent call last):
  File "/home/ops/verdi/ops/coseismic_enumerator/iterate.py", line 80, in <module>
    if __name__ == '__main__': main()
  File "/home/ops/verdi/ops/coseismic_enumerator/iterate.py", line 57, in main
    try: active.process (aoi)
  File "/home/ops/verdi/ops/coseismic_enumerator/active.py", line 117, in process
    track_number=aoi['metadata']['context']['track_number'])
KeyError: 'track_number'
```

**Comment by al-niessner** [comment]
> @al-niessner - deployed, executed and received the below error in `_stderr`:
> 
> ```
> Traceback (most recent call last):
>   File "/home/ops/verdi/ops/coseismic_enumerator/iterate.py", line 80, in <module>
>     if __name__ == '__main__': main()
>   File "/home/ops/verdi/ops/coseismic_enumerator/iterate.py", line 57, in main
>     try: active.process (aoi)
>   File "/home/ops/verdi/ops/coseismic_enumerator/active.py", line 117, in process
>     track_number=aoi['metadata']['context']['track_number'])
> KeyError: 'track_number'
> ```

@marjo-luc the quoted trace back above in this comment means that the track number has moved in the AOI. Interestingly it moved since the test run after including the water mask and now. Was the move intentional or is the move an error or is the enumerator not using the stable location of the track number? Please let me know.

@riverma if the _stdout.txt is still around, can we grab it?

**Comment by cmarshak** [comment]
To the second question, due to instant cleanup of the job directories on factotum, the relevant coseismic job directories are being copied into `/tmp/coseismic-pipeline-job-dirs/<todays_date as YYYY-MM-DD>/<job-dir-name>` every 5 seconds.

**Comment by cmarshak** [comment]
And to follow up on the first question, I saved an old AOITrack dataset on my local machine from January. It appears the `track_number` is in the document where Al is looking so indeed something has changed. Al, this actually something that is written by the enumerator so I can't say for sure where the change occured (in the enumerator or in AOITrack dataset). Here is the document I am looking at:

```
{
  "username": "hysdsops",
  "eventtime": "2019-07-04T17:33:49Z",
  "image_url": null,
  "event_metadata": {
    "depth": 10.5,
    "event id": "ci38443183",
    "label": "M 6.4 - Ridgecrest Earthquake Sequence",
    "latitude": 35.7053333,
    "location": "Ridgecrest Earthquake Sequence",
    "longitude": -117.5038333,
    "magnitude": 6.4,
    "pager_status": "yellow",
    "tsunami warning": 1,
    "usgs information": "https://earthquake.usgs.gov/earthquakes/eventpage/ci38443183"
  },
"context": {
    "_command": "/home/ops/verdi/ops/create_aoi/create_AOI.py",
...
    "localize_urls": [],
    "name": "AOITRACK_eq_usgs_neic_pdl_ci38443183_64",
    "orbit_direction": "asc",
    "runtime_options": {},
    "starttime": "2019-06-04T17:33:49.000",
    "tag": "create_neic_event_aoi",
    "track_number": 64,
    "type": "earthquake",
    "username": "hysdsops"
  }
}
```

**Comment by marjo-luc** [comment]
I don't know why the track number was not included in the most recent aoitracks. The code is still in there. Let me look into it and get back to you.

**Comment by al-niessner** [comment]
> And to follow up on the first question, I saved an old AOITrack dataset on my local machine from January. It appears the `track_number` is in the document where Al is looking so indeed something has changed. Al, this actually something that is written by the enumerator so I can't say for sure where the change occured (in the enumerator or in AOITrack dataset). Here is the document I am looking at:

@cmarshak enumerator passes it forward from the aoi track from a previous request. It is the reading of it from the AOI that is the failure. Hence, the change has to be prior to the enumerator.

**Comment by marjo-luc** [comment]
I'm not sure why the original aoitracks did not have the _track_number_ field. I reran the event evaluator without making any code changes and I was able to produce a collection of aoitracks with the field present. I suspect the older aoitracks were from various testing efforts. I purged them all and generated a new set, so we should be good.

116625192-17d61e00-a8fe-11eb-9858-5d0fa0f92cd1

To see the new aoitracks, open GRQ and facet upon `aoitrack-earthquake` data sets.

**Comment by riverma** [comment]
FYI - have rerun the Enumerator given the recent updated `aoitrack-earthquake` dataset changes, and we've passed the previous `5 seconds` failure point from the last attempt. Shouldn't take more than another hour or so for the Enumerator job to finish (if it succeeds) - will keep monitoring.

**Comment by riverma** [comment]
Enumerator failed due to an inconsistent dataset name within the HySDS `datasets.json` file (`S1-COSEISMIC-GUNW-acq-list-event-iter...` has been updated as part of this PR. I've fixed the entry in the `datasets.json` file.

However, it looks like after the Enumerator ran, the `aoitrack-earthquake` datasets are once again missing the `track` field. I'm receiving the below error once again within seconds of running the Enumerator:

```
    track_number=aoi['metadata']['context']['track_number'])
KeyError: 'track_number'
```

@al-niessner can you confirm that in your updates to the `aoitrack-earthquake` datasets (to update the `endtime`) you're not inadvertently removing the `track` field? 

@marjo-luc - can you think of something else on your end that may explain this change to the `aoitrack-earthquake` dataset?

**Comment by riverma** [comment]
Based on recent feedback from @marjo-luc - it looks like the `orbit_direction` field was also removed. 

@al-niessner it seems highly likely the Enumerator may be inadvertently removing fields in the `aoitrack-earthqake` dataset, though further tests may be needed to fully confirm. Can you double check your code?

**Comment by al-niessner** [comment]
I appreciate your concern that the enumerator is munging the data in the AOI. However there are a couple of reasons why it cannot be the enumerator as you have described the situation:

1. The enumerator has to complete successfully for HySDS to push its changes to the AOI back into ES. Your reports indicate that it has not completed successfully for a while now. If multiple enumerators are running at the same time, then this corruption is expected as stated in the FAQ and many times previously.
2. The enumerator code [update()](https://github.com/aria-jpl/coseismic_enumerator/blob/51645a927681487031316374f22557852050f3d0/active.py#L154-L174) has not changed in 3 months. 4 months if you ignore the change in the label once we knew it was working well enough.
3. A review of the same code shows that it copies the AOI metadata wholesale and does not do it item by item. Hence, if any of the metadata makes it, then all of the metadata makes it.

I had similar problems way back in November when automated triggers were causing many versions of the enumerator to run at the same time. I noticed this while writing the enumerator because when I would facet for my job there would be several others running at the same time but much older versions. I solved the problem by removing the older containers from HySDS.

I would suggest faceting the jobs from yesterday and seeing which and how many of the AOI generators ran. If more than one is found, find out why and reduce it to just the version you want. If you cannot locate the multiple jobs, then purge the AOIs, generate a new, clean set 
of AOIs then check, using ES, every hour if the track number is still there. When you find it has vanished, find all jobs that ran that hour and figure out which is destroying the AOI. I am not sure how long it was between when @marjo-luc created the new set and @riverma ran the enumerator but that time gap is your bound for interval and expected duration of monitoring the AOI in ES.

**Comment by riverma** [comment]
@al-niessner - I've kicked off another Enumerator job while ensuring no other Enumerator containers are running concurrently on the system. Also ensured the `aoitrack-earthquake` datasets have required track info.

Monitoring.🤞

**Review by riverma — APPROVED** [review]
Confirmed fixed in ops.

**Pull request merged**
