### PR TITLE
issue #24 - singular

### LINKED ISSUE #24: Make "singular" Enumeration strategy the default
**Is your feature request related to a problem? Please describe.**
Science users @cmarshak et al requested that the Enumerator should be utilizing a "singular" enumeration strategy as the default, as opposed to the current "intersected" or the "significantly intersected". We'd like to test with this approach. 

**Describe the solution you'd like**
- Create a branch with the "singular" strategy as default, for testing purposes. See "alternatives" section below for caveat. 
- Deploy to ARIA CI/CD to have ready for a test

**Describe alternatives you've considered**
Adding a configuration option to choose between the various modes, but keep "singular" as default. 

@al-niessner - if supporting a configuration item is less than 2 hours of work, please enact that as it provides greater flexibility for the long-term. Understood that ops would have to be cognizant about mode proactively. 

**Additional context**
Reach out to @cmarshak or @riverma for any questions.

### PR DESCRIPTION
**Pull request by al-niessner**
Closes #24

### CODE REVIEW

**Comment by al-niessner** [comment]
Code changes are made.

**Comment by riverma** [comment]
@al-niessner - 

Tested this on our system; however, the Enumerator "completed successfully" within a few seconds without generating any expected acqlists. Could you please investigate and apply a fix if necessary?

**Comment by al-niessner** [comment]
Yes, that is because the AOI that has the future `endtime` has all pre and post events filled. If you wish to process, either delete `event_processing` in AOI or using On-Demand set reset_all to non-zero.

**Comment by riverma** [comment]
Confirmed to work as expected in ops (thanks @cmarshak).

**Pull request merged**
